name: Bootstrapping + releasing fedora rootfs
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * *" # run at the start of every day
  workflow_dispatch:

jobs:
  build-37:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Installing dependencies
        run: sudo apt-get update && sudo apt-get install -y dnf curl

      - name: Adding yum repos for dnf
        run: sudo cp -r configs/yum.repos.d/ /etc/yum.repos.d/

      - name: Adding gpg keys repos for dnf
        run: sudo cp -r configs/rpm-gpg /etc/pki/

      - name: Unpacking + Repacking popos rootfs
        run: sudo bash unpack_iso.sh

      - name: Generating release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::$(date +"%Y.%m.%d_%H-%M")"
      - name: Creating new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          name: Automated rootfs extraction - ${{ steps.tag.outputs.release_tag }}
          body: |
            These are completely **unmodified** rootfs archives for the depthboot builder script.  
            Please download official images at 
          files: |
            /tmp/*.rpm
